<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Barang;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $barangs = [
            ['nama_barang' => 'STABILO BOS', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/3osGGcMtt8804Qgnm9veJjQ3iVLGScUoTw4ZseKs.jpg'],
            ['nama_barang' => 'PULPEN PILOT FASTER', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/zUIz5bWUSSpAI6SdW84SVmMsAWmUZV9BiTqh3YBQ.jpg'],
            ['nama_barang' => 'SPIDOL WHITEBOARD SNOWMAN', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/Sj9x03fEZkvikjkH0ruAFuWsgIoRHzvUDoK8bkCb.jpg'],
            ['nama_barang' => 'SPIDOL WHITEBOARD WARNA', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/qMT9uALOeXtha5FKwhi0hsUrpq5zKg6J9syme3wZ.jpg'],
            ['nama_barang' => 'BALLPOINT BALLINER BIRU', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/F8aPMO0yl3LSdXD42VLxx1LZUI2a0y4tgIpZk333.jpg'],
            ['nama_barang' => 'BALLPOINT BALLINER HITAM', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/dbQRnulbo3OYLTYuc1wordOOiNgFAUMbmkJzkmfR.jpg'],
            ['nama_barang' => 'REFIL BALLPOINT PENTEL HITAM', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'REFIL ROLLER BALL PARKER BLUE 0.7', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'REFIL ROLLER BALL PARKER BLACK 0.7', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BINDER CLIPS NO.105', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BINDER CLIPS NO.200', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/y5jixBFSQrZVrapgnm4psUK0Ks4OfX77E5W64riE.jpg'],
            ['nama_barang' => 'BINDER CLIPS NO.260', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/P34zHZ22Sp3JJ4vO12byWE0dOqlmw7TDlBssCO7Y.jpg'],
            ['nama_barang' => 'BINDER CLIPS NO.155', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TRIGONAL CLIPS NO.5', 'satuan' => 'BOX', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'STAPLER MAX HD 50', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/WPrmk9eomA3bR6kDcHndUhd3A4gtO0xNtb9OS5et.jpg'],
            ['nama_barang' => 'STAPLER MAX HD 10', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'ISI STAPLES MAX NO.10', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TRIGONAL CLIPS NO.3 JOYKO', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BINDER CLIP 107 JOYKO', 'satuan' => 'DOS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BINDER CLIP 111 JOYKO', 'satuan' => 'DOS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BINDER CLIP 155 JOYKO', 'satuan' => 'DOS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BINDER CLIP 200 JOYKO', 'satuan' => 'DOS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BINDER CLIP 260 JOYKO', 'satuan' => 'DOS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BINDER CLIP 105 JOYCO', 'satuan' => 'DOS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'PENGHAPUS PENSIL', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'PENGHAPUS WHITEBOARD', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TIP EX PENTEL', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BUKU FOLIO', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BUKU LEMBAR DISPOSISI', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/elozY77bMR5IofMF1DwYHNaplusTWfZ12TNweecy.jpg'],
            ['nama_barang' => 'BUKU EXPEDISI', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'AGENDA SURAT KELUAR - MASUK', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BOX FILE', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/BWUOokAKEj3tnLJDxlEhVLtfLS8L9zCJQEbWKqGH.jpg'],
            ['nama_barang' => 'SNELHECTER CETAK', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'SNELHECTER PLASTIK SPRING FILE', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'MAP BATIK', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'ODNER KUITANSI', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BISNIS FILE', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'STOP MAP CETAK A4', 'satuan' => 'EKS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'MAP PLASTIK A4', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'MAP PLASTIK PROTECTOR TRANSPARANT', 'satuan' => 'LEMBAR', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'PENGGARIS BESI 60 CM', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'RAUTAN ANGEL', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/DfafoYgwgBe6hD9jOEeSNw1NjQZRi2Av0PJohjE0.jpg'],
            ['nama_barang' => 'CUTTER L 500', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/2re87OekvDfiizByJ02pWLim81hj32sH4ACjoVwK.jpg'],
            ['nama_barang' => 'CUTTER A300 JOYCO', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'ISOLASI 1 X 72 NACHI', 'satuan' => 'ROLL', 'stock' => 0, 'foto' => 'barang/AkwNiPi2bACSr5BsS32YCiqeGb8DbNTyTnIGm4rL.jpg'],
            ['nama_barang' => 'ISOLASI TRANSPARANT 2\'\' NACHI', 'satuan' => 'ROLL', 'stock' => 0, 'foto' => 'barang/1WM9Z6K1rUSppgEMbzNfYtVCGkqXppKtdg7FQXVZ.jpg'],
            ['nama_barang' => 'ISOLASI I 2\'\' X 72 NACHI', 'satuan' => 'ROLL', 'stock' => 0, 'foto' => 'barang/sf0iHFNQuQ49se4nBpjL741KBy36Hx9siP8P860P.jpg'],
            ['nama_barang' => 'LAK BAND LINEN', 'satuan' => 'ROLL', 'stock' => 0, 'foto' => 'barang/M3nesFoKt7yiLbLyoQ21WTPS3SpPg1sbUeCGeO0r.jpg'],
            ['nama_barang' => 'LAK BAND COKLAT', 'satuan' => 'ROLL', 'stock' => 0, 'foto' => 'barang/EBjRvKuYJNbx7Dk4pcLxa7GwiuQ8PBO4HeaF33cG.jpg'],
            ['nama_barang' => 'LEM STIK BANTEX', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/htPd2JiftXd7dqJsOScUrpm2bxcSfw8BsNLJXiRL.jpg'],
            ['nama_barang' => 'DOUBLE FOAM 1 INCHI', 'satuan' => 'ROLL', 'stock' => 0, 'foto' => 'barang/aVVbCUwTsFmtP6aXdb2xEYsdmZlFcmJweb1A19Vl.jpg'],
            ['nama_barang' => 'DOUBLE TAPE 1 2 INCHI', 'satuan' => 'ROLL', 'stock' => 0, 'foto' => 'barang/XnkkQo8kLkxUUV5uGLBrYgqA8A8yIoSE43c04tnj.jpg'],
            ['nama_barang' => 'Isolasi Kertas 2 Nachi', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Isolasi Kertas 1 Nachi', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'HECHNECHESE NO. 3-M (ISI STAPLER)', 'satuan' => 'DOOS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'GUNTING SEDANG', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KALKULATOR', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'REMOVER', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'PERFORATOR KECIL NO.30', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/T8YhvcrgRgmXkCmgwK9wTghjHF13qTW9Dp1qhlrY.jpg'],
            ['nama_barang' => 'DISPENSER TAPE LION DL-50', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS HVS 80 GRAM FOLIO', 'satuan' => 'RIM', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS HVS 80 GRAM A4', 'satuan' => 'RIM', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS HVS 70 GRAM A4', 'satuan' => 'RIM', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS HVS A4 WARNA', 'satuan' => 'RIM', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS CONCORDE 90 GRAM', 'satuan' => 'LEMBAR', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS PEMBUNGKUS', 'satuan' => 'LEMBAR', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS BUFFALO', 'satuan' => 'LEMBAR', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS STIKER UKURAN A4 DOF', 'satuan' => 'RIM', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS STIKER FOLIO GLOSSY', 'satuan' => 'PACK', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'AMPLOP COKLAT KECIL', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'AMPLOP COKLAT BESAR', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'AMPLOP COKLAT SEDANG', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'AMPLOP PAPERLINE NO 90', 'satuan' => 'DOS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS KOP SK', 'satuan' => 'RIM', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS KOP SURAT GARUDA', 'satuan' => 'RIM', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERTAS PIAGAM KOP GARUDA', 'satuan' => 'RIM', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'POST IT Biasa Joyko', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'POST IT SIGN HERE 3M', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'tinta epson 001 black', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson 001 Cyan', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta epson 001 Yellow', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson 001 Magenta', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson 003 Cyan', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson 003 Yellow', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson 003 Magenta', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TINTA L210 EPSON', 'satuan' => 'UNIT', 'stock' => 0, 'foto' => 'barang/eKKB2CgWF0xMHy1pIOezLVuL4qC2m1zLkIcYVO82.jpg'],
            ['nama_barang' => 'TONER HP 80A', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/N7ymFktjNEUENG0wt4nBc1zkl8a2SS04euYSAcDC.jpg'],
            ['nama_barang' => 'TONER HP CE311', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER HP CE312', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER HP CE 313', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER HP CE 310', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER 83 A-COMPATIBLE', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER 202A BLACK', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER 202A CYAN', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER 202A YELLOW', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER 202A MAGENTA', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER 9040 BLACK', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER 9041 CYAN', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER 9042 YELLOW', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER 9043 MAGENTA', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER HP 05 A', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TINTA L15150 BLACK', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TINTA L15150 CYAN', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TINTA L15150 MAGENTA', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TINTA L15150 YELLOW', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER TN 263 BLACK BROTHER', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER TN 263 CYAN BRODHER', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER TN 263 MAGENTA BRODHER', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TONER TN 263 YELLOW BRODHER', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson Black 003', 'satuan' => 'Buah', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson Yellow 003', 'satuan' => 'Buah', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson Cyan 003', 'satuan' => 'Buah', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson Magenta 003', 'satuan' => 'Buah', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson L1455 (Black 664)', 'satuan' => 'Buah', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TINTA CANON G3010 seri tinta GI-790 HITAM', 'satuan' => 'Buah', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TINTA CANON G3010 seri tinta GI_791 CYAN', 'satuan' => 'Buah', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson 001 Warna Cyan', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson 001 Warna Magenta', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson 001 Warna Yellow', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tinta Epson 001 Warna Hitam', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tonner HP 126 A Black', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tonner HP 126 A Cyan', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tonner HP 126 A Yellow', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Tonner HP 126 A Magenta', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'EPSON WF-C5890 BLACK', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'EPSON WF-C5890 CYAN', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'EPSON WF-C5890 YELLOW', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'EPSON WF-C5890 MAGENTA', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TINTA CANON G3010 seri tinta GI-792 Yellow', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TINTA CANON G3010 seri tinta GI-793 Magenta', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'FLASHDISK 32 GB', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'OPTICAL MOUSE USB', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'LAMPU TL 18 WATT', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'LAMPU TL PHILIP 36 WATT', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'LAMPU LED 12 WATT', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/PGOK3wNRM8s5vkYkEb9KmnC8LJG5oyoVyEbI272q.jpg'],
            ['nama_barang' => 'LAMPU LED 25 WATT', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'LAMPU PHILIPS LED 900 LUMEN 10 WATT', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Lampu LED Downlight 7 W 550 Lumen', 'satuan' => 'Buah', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BATERAY SEDANG', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/Z3jGdePhG8jiWtfsea07bfYT4drZ4N2wgwuobKN0.jpg'],
            ['nama_barang' => 'BATERAY UNTUK MIC', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BATTERAY AAA', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/EUfdiyRljph0U2gzce9BV6RVdtdbeSNUMPDAQDre.jpg'],
            ['nama_barang' => 'BATU BATERAI BESAR', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/kk78CDl3UnBJ7zVZwoj9qcrztGaCAnqm7VKm4Z4M.jpg'],
            ['nama_barang' => 'BATU BATERAI AA', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/B0ymZ0sOhHAo04MWp6eaZzhLEjklFgxgAHxkHj2W.jpg'],
            ['nama_barang' => 'SIKAT LANTAI', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'DUST MOP', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'SAPU LIDI TANPA PEGANGAN', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KANEBO', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'MAJUN KILOAN', 'satuan' => 'KG', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TEMPAT SAMPAH INJAK BUNDAR STAINLESS', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TEMPAT SAMPAH INJAK PLASTIK', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'PORSTEX', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/YCoQNrOoVc7j5rJ7fBPOE4xJMQbwk7U3Kgqpbnt8.jpg'],
            ['nama_barang' => 'SABUN PEMBERSIH LANTAI', 'satuan' => 'KEMAS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'PLEDGE LEMON', 'satuan' => 'KEMAS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BEBEK CLOSET', 'satuan' => 'BOTOL', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'CIF CAIR', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/gRA91vFtac9foDh4trKV3Q6K2SIXyrVtbwfqmCVz.jpg'],
            ['nama_barang' => 'REFILL PENGHARUM RUANGAN', 'satuan' => 'KEMAS', 'stock' => 0, 'foto' => 'barang/uzxC00ukBwXToKGGn7UOZBbm1nEsQOp3cbhjs9Lz.jpg'],
            ['nama_barang' => 'KAPUR BARUS BOLA', 'satuan' => 'PACK', 'stock' => 0, 'foto' => 'barang/KKROzHJHDnRUcF6ZwzIwCRsT0E0EuzDnSETDD6vk.jpg'],
            ['nama_barang' => 'KAPUR BARUS GANTUNG', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/bvtevPwfQkNxGNC4i9mC3a1fKQaASjbAKsuDVuNL.jpg'],
            ['nama_barang' => 'TEMPAT SABUN', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BOKS BESAR LOGO BPS', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'BENDERA MERAH PUTIH', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/gratigzSw3Ltc90vorARlPKS06t4BoulwmCWGdFl.jpg'],
            ['nama_barang' => 'TISSUE KOTAK SEE U', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/aTshnUqxmLtBeQLUzDFp6YXWOoJsAOupCTExOmaZ.png'],
            ['nama_barang' => 'TISSUE GULUNG SEE U', 'satuan' => 'ROLL', 'stock' => 0, 'foto' => 'barang/3s9VHZvQc736e6uXJ8ajCk0B1V5bOcFc2UWmDFRh.jpg'],
            ['nama_barang' => 'TISSUE WAJAH', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TEMPAT TISSUE KOTAK', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/h3wZBeDLHoZnPnPKaqYZmYAqImtuYtuJNXdP9tOg.jpg'],
            ['nama_barang' => 'TEMPAT TISSUE GULUNG', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/NcILA8ohByC67CHqxWdTXNoiivxdNdOabcDvFjTT.jpg'],
            ['nama_barang' => 'AKRILIK', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'CAIRAN WD', 'satuan' => 'BOTOL', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TAMPAR PENGEREK BENDERA', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/je7sQsS8VHWfq5bcyIqlhwNADJZd39NkPSVN4xoY.jpg'],
            ['nama_barang' => 'SABUN CUCI PIRING', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => 'barang/NcPiMjXShMC2qWMNtueOiOqbX8CfpW3vIGK9fxF0.jpg'],
            ['nama_barang' => 'SPIN MOP', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'SARUNG TANGAN KARET', 'satuan' => 'PACK', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'SABUN PENCUCI TANGAN YURI', 'satuan' => 'BUNGKUS', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KERANJANG SAMPAH', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'PLAKAT BPS', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KONDOM KAIN MIC', 'satuan' => 'PACK', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'GELANG MICROPHONE', 'satuan' => 'BUAH', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KANTONG SAMPAH', 'satuan' => 'PACK', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'GODIE BAG SE2026', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'ISI CUTTER (1)', 'satuan' => 'PAX', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'LEMBAR DAFTAR HADIR', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'Pigora A4', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TOPI SE2026', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'TUMBLER SE2026', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'KAOS SE2026', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'PAYUNG SE2026', 'satuan' => 'Pcs', 'stock' => 0, 'foto' => null],
            ['nama_barang' => 'MUG SE2026', 'satuan' => 'PCS', 'stock' => 0, 'foto' => null],
        ];

        foreach ($barangs as $item) {
            Barang::create($item);
        }
    }
}